import { Demand } from "@/types/demand";

export const mockDemands: Demand[] = [
  {
    id: "1",
    title: "Implementar login com Google",
    description: "Adicionar autenticação OAuth2 com Google para facilitar o acesso dos usuários",
    type: "feature",
    priority: "high",
    status: "in-progress",
    system: "toqweb",
    responsible: "João Silva",
    createdAt: new Date("2025-10-01"),
    updatedAt: new Date("2025-10-07"),
    sprint: "Sprint 23",
    storyPoints: 8,
    dueDate: new Date("2025-10-15"),
    tags: ["autenticação", "oauth"],
    checklist: [
      { id: "1", text: "Configurar OAuth no Google Console", completed: true },
      { id: "2", text: "Implementar callback de autenticação", completed: true },
      { id: "3", text: "Testar fluxo completo", completed: false },
    ],
    attachments: [
      {
        id: "1",
        name: "Documentação OAuth Google",
        type: "link",
        url: "https://developers.google.com/identity/protocols/oauth2",
        uploadedAt: new Date("2025-10-01"),
      },
    ],
    timeline: [
      {
        id: "1",
        type: "created",
        description: "Demanda criada",
        user: "João Silva",
        timestamp: new Date("2025-10-01T09:00:00"),
      },
      {
        id: "2",
        type: "status_change",
        description: "Status alterado para Em Andamento",
        user: "João Silva",
        timestamp: new Date("2025-10-02T10:30:00"),
      },
    ],
  },
  {
    id: "2",
    title: "Corrigir bug no relatório de vendas",
    description: "Os valores totais estão sendo calculados incorretamente quando há descontos",
    type: "bug",
    priority: "high",
    status: "todo",
    system: "toqvenda",
    responsible: "Maria Santos",
    createdAt: new Date("2025-10-05"),
    updatedAt: new Date("2025-10-05"),
    sprint: "Sprint 23",
    storyPoints: 5,
    tags: ["crítico", "vendas"],
    timeline: [
      {
        id: "1",
        type: "created",
        description: "Bug reportado",
        user: "Maria Santos",
        timestamp: new Date("2025-10-05T14:00:00"),
      },
    ],
  },
  {
    id: "3",
    title: "Atualizar bibliotecas do sistema",
    description: "Atualizar dependências para versões mais recentes por questões de segurança",
    type: "repair",
    priority: "medium",
    status: "testing",
    system: "gmax",
    responsible: "Pedro Costa",
    createdAt: new Date("2025-09-28"),
    updatedAt: new Date("2025-10-06"),
    sprint: "Sprint 22",
    storyPoints: 3,
    timeline: [
      {
        id: "1",
        type: "created",
        description: "Demanda criada",
        user: "Pedro Costa",
        timestamp: new Date("2025-09-28T11:00:00"),
      },
      {
        id: "2",
        type: "status_change",
        description: "Status alterado para Em Teste",
        user: "Pedro Costa",
        timestamp: new Date("2025-10-06T16:00:00"),
      },
    ],
  },
  {
    id: "4",
    title: "Adicionar exportação para Excel",
    description: "Permitir exportar relatórios em formato Excel (.xlsx)",
    type: "feature",
    priority: "medium",
    status: "todo",
    system: "toqblend",
    responsible: "Ana Oliveira",
    createdAt: new Date("2025-10-03"),
    updatedAt: new Date("2025-10-03"),
    sprint: "Sprint 24",
    storyPoints: 5,
    tags: ["relatórios", "export"],
  },
  {
    id: "5",
    title: "Erro ao salvar configurações",
    description: "Sistema apresenta erro 500 ao tentar salvar configurações do usuário",
    type: "bug",
    priority: "high",
    status: "in-progress",
    system: "t5",
    responsible: "João Silva",
    createdAt: new Date("2025-10-06"),
    updatedAt: new Date("2025-10-07"),
    sprint: "Sprint 23",
    storyPoints: 3,
    tags: ["erro-500", "configurações"],
  },
  {
    id: "6",
    title: "Melhorar performance do dashboard",
    description: "Dashboard está lento ao carregar gráficos com muitos dados",
    type: "repair",
    priority: "low",
    status: "todo",
    system: "t10",
    responsible: "Maria Santos",
    createdAt: new Date("2025-09-30"),
    updatedAt: new Date("2025-09-30"),
    sprint: "Sprint 24",
    storyPoints: 8,
    tags: ["performance", "otimização"],
  },
  {
    id: "7",
    title: "Integração com sistema de pagamento",
    description: "Implementar integração com gateway de pagamento PIX",
    type: "feature",
    priority: "high",
    status: "done",
    system: "ecopdv",
    responsible: "Pedro Costa",
    createdAt: new Date("2025-09-20"),
    updatedAt: new Date("2025-10-04"),
    sprint: "Sprint 22",
    storyPoints: 13,
    dueDate: new Date("2025-10-05"),
    tags: ["pagamento", "pix"],
    timeline: [
      {
        id: "1",
        type: "created",
        description: "Demanda criada",
        user: "Pedro Costa",
        timestamp: new Date("2025-09-20T09:00:00"),
      },
      {
        id: "2",
        type: "status_change",
        description: "Status alterado para Concluído",
        user: "Pedro Costa",
        timestamp: new Date("2025-10-04T17:00:00"),
      },
    ],
  },
  {
    id: "8",
    title: "Corrigir layout mobile",
    description: "Alguns elementos não estão responsivos em telas pequenas",
    type: "bug",
    priority: "medium",
    status: "testing",
    system: "toqped",
    responsible: "Ana Oliveira",
    createdAt: new Date("2025-10-02"),
    updatedAt: new Date("2025-10-06"),
    sprint: "Sprint 23",
    storyPoints: 2,
    tags: ["mobile", "responsivo"],
  },
];
