import { Demand } from "@/types/demand";

export const mockDemands: Demand[] = [
  {
    id: "1",
    title: "Implementar login com Google",
    description: "Adicionar autenticação OAuth2 com Google para facilitar o acesso dos usuários",
    type: "feature",
    priority: "high",
    status: "in-progress",
    system: "toqweb",
    responsible: "João Silva",
    createdAt: new Date("2025-10-01"),
    updatedAt: new Date("2025-10-07"),
  },
  {
    id: "2",
    title: "Corrigir bug no relatório de vendas",
    description: "Os valores totais estão sendo calculados incorretamente quando há descontos",
    type: "bug",
    priority: "high",
    status: "todo",
    system: "toqvenda",
    responsible: "Maria Santos",
    createdAt: new Date("2025-10-05"),
    updatedAt: new Date("2025-10-05"),
  },
  {
    id: "3",
    title: "Atualizar bibliotecas do sistema",
    description: "Atualizar dependências para versões mais recentes por questões de segurança",
    type: "repair",
    priority: "medium",
    status: "testing",
    system: "gmax",
    responsible: "Pedro Costa",
    createdAt: new Date("2025-09-28"),
    updatedAt: new Date("2025-10-06"),
  },
  {
    id: "4",
    title: "Adicionar exportação para Excel",
    description: "Permitir exportar relatórios em formato Excel (.xlsx)",
    type: "feature",
    priority: "medium",
    status: "todo",
    system: "toqblend",
    responsible: "Ana Oliveira",
    createdAt: new Date("2025-10-03"),
    updatedAt: new Date("2025-10-03"),
  },
  {
    id: "5",
    title: "Erro ao salvar configurações",
    description: "Sistema apresenta erro 500 ao tentar salvar configurações do usuário",
    type: "bug",
    priority: "high",
    status: "in-progress",
    system: "t5",
    responsible: "João Silva",
    createdAt: new Date("2025-10-06"),
    updatedAt: new Date("2025-10-07"),
  },
  {
    id: "6",
    title: "Melhorar performance do dashboard",
    description: "Dashboard está lento ao carregar gráficos com muitos dados",
    type: "repair",
    priority: "low",
    status: "todo",
    system: "t10",
    responsible: "Maria Santos",
    createdAt: new Date("2025-09-30"),
    updatedAt: new Date("2025-09-30"),
  },
  {
    id: "7",
    title: "Integração com sistema de pagamento",
    description: "Implementar integração com gateway de pagamento PIX",
    type: "feature",
    priority: "high",
    status: "done",
    system: "ecopdv",
    responsible: "Pedro Costa",
    createdAt: new Date("2025-09-20"),
    updatedAt: new Date("2025-10-04"),
  },
  {
    id: "8",
    title: "Corrigir layout mobile",
    description: "Alguns elementos não estão responsivos em telas pequenas",
    type: "bug",
    priority: "medium",
    status: "testing",
    system: "toqped",
    responsible: "Ana Oliveira",
    createdAt: new Date("2025-10-02"),
    updatedAt: new Date("2025-10-06"),
  },
];
